server:
  port: 9090

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: false
        format_sql: true
        jdbc:
          time_zone: UTC

  datasource:
    url: jdbc:mysql://localhost:3306/account?useSSL=false
    username: root
    password: root



